### ISSUE TITLE
Discarding data changes results in resetting the values to the default ones

### ISSUE THREAD

**Issue by godrose** [LogoFX/Samples.Universal#4]
Repro steps:

- Start the app
- Provide valid username and password
- Log into the app
- Select an item
- Edit some of the fields
- Discard the changes

**Expected**:
*The values are reset to the original ones*
**Actual**:
*The values are reset to the default ones (`int` -> `0`, `string` -> `null`) etc.*

**Comment by dmitrybublik** [comment]
Fixed
